export const INITIAL_MARKETS = [
  {
    id: 1,
    category: 'isa',
    categoryName: 'Classroom',
    icon: '⏱️',
    title: 'How many minutes before William talks about volunteering?',
    description: 'Resolves to "< 15 mins" if William mentions volunteering within the first 15 minutes of lecture, or "≥ 15 mins" if later or never.',
    yesPrice: 0.68,
    noPrice: 0.32,
    yesLabel: '< 15 mins',
    noLabel: '≥ 15 mins',
    volume: 56800,
    endDate: 'Today\'s Lecture',
    image: '/logo.png',
    featured: true
  },
  {
    id: 2,
    category: 'football',
    categoryName: 'Football',
    icon: '⚽',
    title: 'Will LOSC Lille finish in Ligue 1 Top 3 this season?',
    description: 'Resolves to Yes if LOSC Lille qualifies directly for the UEFA Champions League group stage.',
    yesPrice: 0.58,
    noPrice: 0.42,
    yesLabel: 'Yes',
    noLabel: 'No',
    volume: 34120,
    endDate: 'May 18, 2026',
    image: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 3,
    category: 'isa',
    categoryName: 'ISA & Campus',
    icon: '🎟️',
    title: 'Will the ISA Annual Sports Gala tickets sell out within 24 hours?',
    description: 'BDS Gala ticket sales opening prediction for master and bachelor students.',
    yesPrice: 0.84,
    noPrice: 0.16,
    yesLabel: 'Yes',
    noLabel: 'No',
    volume: 18900,
    endDate: 'Apr 10, 2026',
    image: '/logo.png'
  },
  {
    id: 4,
    category: 'olympics',
    categoryName: 'Global Sports',
    icon: '🏆',
    title: 'Will France reach the Final of the 2026 FIFA World Cup?',
    description: 'Resolves to Yes if the French National Team plays the 2026 World Cup Final in MetLife Stadium.',
    yesPrice: 0.41,
    noPrice: 0.59,
    yesLabel: 'Yes',
    noLabel: 'No',
    volume: 76500,
    endDate: 'Jul 19, 2026',
    image: 'https://images.unsplash.com/photo-1518091043644-c1d4457512c6?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 5,
    category: 'basketball',
    categoryName: 'Basketball',
    icon: '🏀',
    title: 'Will the ISA 3x3 Basketball Team make the Regional Final Four?',
    description: 'FFSU Regional Championship in Villeneuve d\'Ascq.',
    yesPrice: 0.63,
    noPrice: 0.37,
    yesLabel: 'Yes',
    noLabel: 'No',
    volume: 12400,
    endDate: 'Apr 30, 2026',
    image: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 6,
    category: 'campus',
    categoryName: 'Student Life',
    icon: '🍻',
    title: 'Will the BDS organise an ISA Ski Trip to Val Thorens in 2027?',
    description: 'Annual winter semester sports retreat proposition by the Bureau des Sports.',
    yesPrice: 0.89,
    noPrice: 0.11,
    yesLabel: 'Yes',
    noLabel: 'No',
    volume: 9800,
    endDate: 'Dec 15, 2026',
    image: 'https://images.unsplash.com/photo-1551524559-8af4e6624178?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 7,
    category: 'isa',
    categoryName: 'ISA & Campus',
    icon: '📊',
    title: 'Will the class average in Sport Economics & Finance be above 14/20?',
    description: 'Semester exam graded across all ISA Master 1 students.',
    yesPrice: 0.47,
    noPrice: 0.53,
    yesLabel: 'Yes',
    noLabel: 'No',
    volume: 21300,
    endDate: 'Jun 12, 2026',
    image: '/logo.png'
  },
  {
    id: 8,
    category: 'football',
    categoryName: 'Football',
    icon: '👑',
    title: 'Will Kylian Mbappé win the 2026 Ballon d\'Or?',
    description: 'Resolves to Yes if France Football awards the Ballon d\'Or to Kylian Mbappé.',
    yesPrice: 0.52,
    noPrice: 0.48,
    yesLabel: 'Yes',
    noLabel: 'No',
    volume: 64200,
    endDate: 'Oct 30, 2026',
    image: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 9,
    category: 'olympics',
    categoryName: 'Global Sports',
    icon: '🎾',
    title: 'Will Carlos Alcaraz win the 2026 French Open (Roland-Garros)?',
    description: 'Men\'s singles tournament at Stade Roland Garros, Paris.',
    yesPrice: 0.65,
    noPrice: 0.35,
    yesLabel: 'Yes',
    noLabel: 'No',
    volume: 28900,
    endDate: 'Jun 07, 2026',
    image: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?auto=format&fit=crop&w=400&q=80'
  },
  {
    id: 10,
    category: 'isa',
    categoryName: 'ISA & Campus',
    icon: '🎓',
    title: 'Will ISA win the 2026 Lille Inter-University Sports Championship?',
    description: 'Resolves to Yes if ISA finishes 1st overall in the Université de Lille tournament.',
    yesPrice: 0.72,
    noPrice: 0.28,
    yesLabel: 'Yes',
    noLabel: 'No',
    volume: 48250,
    endDate: 'May 24, 2026',
    image: '/logo.png'
  }
];

export const MOCK_LEADERBOARD = [
  { rank: 1, name: 'Thomas Bernard', promo: 'ISA M2', balance: 14820, badge: '🥇' },
  { rank: 2, name: 'Camille Renault', promo: 'ISA M1', balance: 11450, badge: '🥈' },
  { rank: 3, name: 'Lucas Dubois', promo: 'ISA L3', balance: 9380, badge: '🥉' },
  { rank: 4, name: 'Emma Lefebvre', promo: 'ISA M2', balance: 7240, badge: '⭐' },
  { rank: 5, name: 'Alexandre Petit', promo: 'ISA M1', balance: 5120, badge: '⭐' },
  { rank: 6, name: 'Inès Martin', promo: 'ISA L3', balance: 3400, badge: '⭐' },
  { rank: 7, name: 'Maxime Leroy', promo: 'ISA M1', balance: 2150, badge: '⭐' },
  { rank: 8, name: 'Jules Moreau (You)', promo: 'ISA M1', balance: 1000, badge: '🎓', isUser: true },
  { rank: 9, name: 'Sophie Laurent', promo: 'ISA M2', balance: 850, badge: '' },
  { rank: 10, name: 'Antoine Roux', promo: 'ISA L3', balance: 620, badge: '' },
];
