-- =========================================================
-- IsaMarket - Supabase Database Schema
-- Run this in the Supabase SQL Editor to set up your tables!
-- =========================================================

-- 1. Profiles Table (Holds student user balance & info)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  full_name TEXT DEFAULT 'Student',
  promo TEXT DEFAULT 'ISA M1',
  squid_balance BIGINT DEFAULT 1000 CHECK (squid_balance >= 0),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Turn on Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Policies for Profiles
CREATE POLICY "Public profiles are viewable by everyone." 
  ON public.profiles FOR SELECT USING (true);

CREATE POLICY "Users can update their own profile." 
  ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Trigger: Automatically create a profile when a new student signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, squid_balance)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)),
    1000 -- Initial free 1,000 Squid grant!
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- 2. Markets Table (Prediction markets list)
CREATE TABLE IF NOT EXISTS public.markets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL DEFAULT 'isa', -- 'isa', 'football', 'basketball', 'olympics', 'campus'
  category_name TEXT NOT NULL DEFAULT 'ISA & Campus',
  icon TEXT DEFAULT '🎓',
  yes_price NUMERIC(3, 2) DEFAULT 0.50,
  no_price NUMERIC(3, 2) DEFAULT 0.50,
  yes_label TEXT DEFAULT 'Yes',
  no_label TEXT DEFAULT 'No',
  volume BIGINT DEFAULT 0,
  end_date TEXT DEFAULT 'June 2026',
  image_url TEXT,
  featured BOOLEAN DEFAULT false,
  status TEXT DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'RESOLVED_YES', 'RESOLVED_NO', 'CANCELLED')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.markets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Markets are readable by all authenticated and anon users."
  ON public.markets FOR SELECT USING (true);


-- 3. Bets Table (User positions and orders)
CREATE TABLE IF NOT EXISTS public.bets (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  market_id BIGINT REFERENCES public.markets(id) ON DELETE CASCADE NOT NULL,
  market_title TEXT NOT NULL,
  outcome TEXT NOT NULL, -- e.g. '< 15 mins' or 'YES'
  amount BIGINT NOT NULL CHECK (amount > 0),
  price NUMERIC(3, 2) NOT NULL,
  shares NUMERIC(10, 2) NOT NULL,
  payout NUMERIC(10, 2) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.bets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own bets."
  ON public.bets FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own bets."
  ON public.bets FOR INSERT WITH CHECK (auth.uid() = user_id);


-- =========================================================
-- 4. Initial Seed Data (Classroom William Bet & Sports)
-- =========================================================
INSERT INTO public.markets (id, title, description, category, category_name, icon, yes_price, no_price, yes_label, no_label, volume, end_date, image_url, featured)
VALUES
  (1, 'How many minutes before William talks about volunteering?', 'Resolves to "< 15 mins" if William mentions volunteering within the first 15 minutes of lecture, or "≥ 15 mins" if later or never.', 'isa', 'Classroom', '⏱️', 0.68, 0.32, '< 15 mins', '≥ 15 mins', 56800, 'Today''s Lecture', '/logo.png', true),
  (2, 'Will LOSC Lille finish in Ligue 1 Top 3 this season?', 'Resolves to Yes if LOSC Lille qualifies directly for the UEFA Champions League group stage.', 'football', 'Football', '⚽', 0.58, 0.42, 'Yes', 'No', 34120, 'May 18, 2026', 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=400&q=80', false),
  (3, 'Will the ISA Annual Sports Gala tickets sell out within 24 hours?', 'BDS Gala ticket sales opening prediction for master and bachelor students.', 'isa', 'ISA & Campus', '🎟️', 0.84, 0.16, 'Yes', 'No', 18900, 'Apr 10, 2026', '/logo.png', false),
  (4, 'Will France reach the Final of the 2026 FIFA World Cup?', 'Resolves to Yes if the French National Team plays the 2026 World Cup Final in MetLife Stadium.', 'olympics', 'Global Sports', '🏆', 0.41, 0.59, 'Yes', 'No', 76500, 'Jul 19, 2026', 'https://images.unsplash.com/photo-1518091043644-c1d4457512c6?auto=format&fit=crop&w=400&q=80', false),
  (5, 'Will the ISA 3x3 Basketball Team make the Regional Final Four?', 'FFSU Regional Championship in Villeneuve d''Ascq.', 'basketball', 'Basketball', '🏀', 0.63, 0.37, 'Yes', 'No', 12400, 'Apr 30, 2026', 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=400&q=80', false)
ON CONFLICT (id) DO NOTHING;
